name: gsearch
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311ha68e1ae_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.5.7=h56e8100_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py311h7d9ee11_3
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.0.7=py311h005e61a_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.7=py311h12c1d0e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fonttools=4.39.3=py311ha68e1ae_0
  - freetype=2.12.1=h546665d_1
  - gettext=0.21.1=h5728263_0
  - glib=2.76.2=h12be248_0
  - glib-tools=2.76.2=h12be248_0
  - gst-plugins-base=1.22.0=h001b923_2
  - gstreamer=1.22.0=h6b5321d_2
  - icu=72.1=h63175ca_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h57928b3_46319
  - ipykernel=6.22.0=pyh025b116_0
  - ipython=8.13.2=pyh08f2357_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py311h1ea47a8_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.5.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py311h005e61a_1
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libclang=16.0.3=default_h8b4101f_0
  - libclang13=16.0.3=default_h45d3cf4_0
  - libdeflate=1.18=hcfcfb64_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.76.2=he8f3873_0
  - libhwloc=2.9.1=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - liblapack=3.9.0=16_win64_mkl
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.40.0=hcfcfb64_1
  - libtiff=4.5.0=h6c8260b_6
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.0=hcfcfb64_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.4=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_4
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.2=py311ha68e1ae_0
  - matplotlib=3.7.1=py311h1ea47a8_0
  - matplotlib-base=3.7.1=py311h6e989c2_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=1.0.0=pyh8b2e9e2_0
  - nbclient=0.7.4=pyhd8ed1ab_0
  - nbconvert-core=7.3.1=pyhd8ed1ab_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numpy=1.24.3=py311h0b4df5a_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.1.0=hcfcfb64_3
  - packaging=23.1=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py311hc67b2de_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.5=py311ha68e1ae_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py311h125bc19_3
  - pyqt5-sip=12.11.0=py311h12c1d0e_3
  - pyrsistent=0.19.3=py311ha68e1ae_0
  - python=3.11.3=h2628c8c_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pywin32=304=py311h12c1d0e_2
  - pywinpty=2.0.10=py311h12c1d0e_0
  - pyyaml=6.0=py311ha68e1ae_5
  - pyzmq=25.0.2=py311h7b3f143_0
  - qt-main=5.15.8=h7f2b912_10
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - send2trash=1.8.2=pyh08f2357_0
  - setuptools=67.7.2=pyhd8ed1ab_0
  - sip=6.7.9=py311h12c1d0e_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.9.0=h91493d7_0
  - terminado=0.17.0=pyh08f2357_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3=py311ha68e1ae_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=hb25d44b_16
  - vc14_runtime=14.34.31931=h5081d32_16
  - vs2015_runtime=14.34.31931=hed1258a_16
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - winpty=0.4.3=4
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zstd=1.5.2=h12be248_6
  - pip:
    - altair==4.2.2
    - blinker==1.6.2
    - cachetools==5.3.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - gitdb==4.0.10
    - gitpython==3.1.31
    - iso3166==2.1.1
    - markdown-it-py==2.2.0
    - mdurl==0.1.2
    - pandas==2.0.1
    - protobuf==3.20.3
    - pyarrow==12.0.0
    - pydeck==0.8.1b0
    - pympler==1.0.1
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - requests==2.30.0
    - rich==13.3.5
    - smmap==5.0.0
    - streamlit==1.22.0
    - tenacity==8.2.2
    - toolz==0.12.0
    - tzdata==2023.3
    - tzlocal==4.3
    - urllib3==2.0.2
    - validators==0.20.0
    - watchdog==3.0.0
prefix: C:\Users\lisa.hornung\anaconda3\envs\gsearch
